default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

development:
  <<: *default
  database: data_analyzer_development

test:
  <<: *default
  database: data_analyzer_test

production:
  <<: *default
  database: data_analyzer_production
  url: <%= ENV.fetch("DATABASE_URL") %>
