# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  user: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>

development:
  <<: *default
  database: data_analyzer_development

test:
  <<: *default
  database: data_analyzer_test

production:
  <<: *default
  database: data_analyzer_production
  pool: <%= ENV.fetch("DATABASE_POOL", 10) %>
